import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api';
type Channel = { id:string; title:string; url:string; avatar_url?:string; video_count:number; added_at:string };
type Video = { id:string; title:string; youtube_video_id:string; published_at?:string; video_type:string; status:string; retry_count:number; last_error?:string; subtitle_path?:string; subtitles:any[] };
type YouTubeConfig = { configured:boolean };
const request = async (path:string, init?:RequestInit) => { const response=await fetch(`${API}${path}`,{headers:{'Content-Type':'application/json'},...init}); if(!response.ok)throw new Error((await response.json().catch(()=>null))?.detail||`Lỗi ${response.status}`); return response.json(); };

function Badge({status}:{status:string}) { return <span className={`badge ${status}`}>{status.replace('_',' ')}</span>; }
function ApiKeySetup({configured,onSaved}:{configured:boolean;onSaved:()=>void}) {
  const [apiKey,setApiKey]=useState(''); const [message,setMessage]=useState('');
  const save=async(event:React.FormEvent)=>{event.preventDefault();setMessage('');try{await request('/config/youtube',{method:'PUT',body:JSON.stringify({api_key:apiKey})});setApiKey('');setMessage('Đã lưu API key. Các job mới sẽ dùng key này.');onSaved();}catch(error:any){setMessage(error.message);}};
  return <section className="settings api-key-settings"><h2>{configured?'Thay YouTube API key':'Cấu hình YouTube API key'}</h2><p>Key được lưu cục bộ trong <code>.env</code> và không hiển thị lại sau khi lưu.</p><form onSubmit={save}><label>API key<input type="password" value={apiKey} onChange={event=>setApiKey(event.target.value)} minLength={10} autoComplete="off" placeholder="AIza..." required/></label><button>Lưu API key</button></form>{message&&<p className={message.startsWith('Đã')?'notice':'error'}>{message}</p>}</section>;
}
function Dashboard({select}:{select:(channel:Channel)=>void}) {
  const [stats,setStats]=useState<any>({}); const [channels,setChannels]=useState<Channel[]>([]); const [url,setUrl]=useState(''); const [error,setError]=useState(''); const [youtube,setYoutube]=useState<YouTubeConfig>();
  const refresh=()=>Promise.all([request('/dashboard'),request('/channels'),request('/config/youtube')]).then(([dashboard,items,config])=>{setStats(dashboard);setChannels(items);setYoutube(config);}).catch(error=>setError(error.message));
  useEffect(()=>{void refresh();},[]);
  const add=async(event:React.FormEvent)=>{event.preventDefault();setError('');try{await request('/channels',{method:'POST',body:JSON.stringify({url})});setUrl('');refresh();}catch(error:any){setError(error.message);}};
  return <main><header><div><p className="eyebrow">QUẢN LÝ CAPTION</p><h1>YouTube Subtitle Manager</h1></div><span className="api">API connected</span></header><ApiKeySetup configured={youtube?.configured??false} onSaved={refresh}/><section className="metrics">{[['Kênh',stats.channels],['Tổng video',stats.videos],['Đã có sub',stats.completed],['Lỗi / Blocked',stats.failed],['Không có sub',stats.no_subtitle],['Job đang chờ',stats.running_jobs]].map(([label,value])=><div className="metric" key={String(label)}><small>{label}</small><strong>{value??'-'}</strong></div>)}</section><section className="add"><div><h2>Thêm kênh YouTube</h2><p>Dán URL dạng @handle, /channel/ID, /user/ hoặc custom URL.</p></div><form onSubmit={add}><input value={url} onChange={event=>setUrl(event.target.value)} placeholder="https://www.youtube.com/@channelname" required/><button>Thêm kênh</button></form>{error&&<p className="error">{error}</p>}</section><section><div className="section-title"><h2>Kênh đang quản lý</h2><button className="secondary" onClick={refresh}>Làm mới</button></div><div className="channels">{channels.map(channel=><button className="channel" onClick={()=>select(channel)} key={channel.id}>{channel.avatar_url?<img src={channel.avatar_url}/>:<i/>}<span><b>{channel.title}</b><small>{channel.video_count} video · thêm {new Date(channel.added_at).toLocaleDateString('vi-VN')}</small></span><em>Chi tiết →</em></button>)}{!channels.length&&<div className="empty">Chưa có kênh nào. Hãy thêm URL để bắt đầu.</div>}</div></section></main>;
}
function ChannelPage({channel,back}:{channel:Channel;back:()=>void}) {
  const [detail,setDetail]=useState<any>();const [videos,setVideos]=useState<Video[]>([]);const [status,setStatus]=useState('');const [message,setMessage]=useState('');
  const load=()=>Promise.all([request(`/channels/${channel.id}`),request(`/channels/${channel.id}/videos${status?`?status=${status}`:''}`)]).then(([channelDetail,items])=>{setDetail(channelDetail);setVideos(items);}).catch(error=>setMessage(error.message)); useEffect(()=>{void load();},[status]);
  const act=(path:string,body?:any)=>request(path,{method:'POST',body:body?JSON.stringify(body):undefined}).then(()=>{setMessage('Đã thêm vào hàng đợi.');load();}).catch(error=>setMessage(error.message));
  const saveSettings=(event:React.FormEvent)=>{event.preventDefault();const form=new FormData(event.currentTarget as HTMLFormElement);const preferred_languages=String(form.get('languages')).split(',').map(value=>value.trim()).filter(Boolean);request(`/channels/${channel.id}/settings`,{method:'PUT',body:JSON.stringify({preferred_languages,subtitle_preference:form.get('kind'),allow_translation:form.get('translate')==='on',export_formats:[...form.getAll('format')],sync_interval_hours:Number(form.get('interval'))})}).then(()=>setMessage('Đã lưu cấu hình.')).catch(error=>setMessage(error.message));};
  if(!detail)return <main>Đang tải…</main>;const settings=detail.settings;
  return <main><button className="back" onClick={back}>← Tất cả kênh</button><header className="channel-head">{detail.avatar_url&&<img src={detail.avatar_url}/>}<div><p className="eyebrow">CHANNEL</p><h1>{detail.title}</h1><a href={detail.url} target="_blank">{detail.youtube_channel_id}</a></div></header><div className="actions"><button onClick={()=>act(`/channels/${channel.id}/scan`,{mode:'all'})}>Quét toàn bộ</button><button onClick={()=>act(`/channels/${channel.id}/sync`)}>Đồng bộ video mới</button><button className="secondary" onClick={()=>act(`/channels/${channel.id}/scan`,{mode:'retryable'})}>Xử lý lỗi / thiếu sub</button></div>{message&&<p className="notice">{message}</p>}<section className="settings"><h2>Cấu hình subtitle</h2><form onSubmit={saveSettings}><label>Ưu tiên ngôn ngữ<input name="languages" defaultValue={settings.preferred_languages.join(', ')}/></label><label>Loại sub<select name="kind" defaultValue={settings.subtitle_preference}><option value="any">Bất kỳ</option><option value="manual">Thủ công</option><option value="auto">Tự động</option></select></label><label>Đồng bộ mỗi (giờ)<input name="interval" type="number" min="1" max="720" defaultValue={settings.sync_interval_hours}/></label><label className="check"><input name="translate" type="checkbox" defaultChecked={settings.allow_translation}/> Cho phép dịch YouTube</label><fieldset><legend>Xuất</legend>{['srt','vtt','txt','json','csv'].map(format=><label className="check" key={format}><input type="checkbox" name="format" value={format} defaultChecked={settings.export_formats.includes(format)}/>{format.toUpperCase()}</label>)}</fieldset><button>Lưu cấu hình</button></form></section><section><div className="section-title"><h2>Video ({videos.length})</h2><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">Mọi trạng thái</option>{['pending','queued','processing','completed','no_subtitle','language_unavailable','failed','blocked','skipped'].map(value=><option key={value}>{value}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Video</th><th>Ngày</th><th>Loại</th><th>Trạng thái</th><th>Retry / lỗi</th><th/></tr></thead><tbody>{videos.map(video=><tr key={video.id}><td><b>{video.title}</b><small>{video.youtube_video_id}</small></td><td>{video.published_at&&new Date(video.published_at).toLocaleDateString('vi-VN')}</td><td>{video.video_type}</td><td><Badge status={video.status}/></td><td>{video.retry_count}{video.last_error&&<small className="error">{video.last_error}</small>}</td><td><button className="secondary" onClick={()=>act(`/videos/${video.id}/download?force=true`)}>Tải lại</button></td></tr>)}</tbody></table></div></section></main>;
}
function JobsPage({back}:{back:()=>void}) { const [jobs,setJobs]=useState<any[]>([]);const [logs,setLogs]=useState<any[]>([]);const [error,setError]=useState('');const load=()=>Promise.all([request('/jobs'),request('/logs')]).then(([items,recent])=>{setJobs(items);setLogs(recent);}).catch(error=>setError(error.message));useEffect(()=>{void load();},[]);const control=(id:string,action:string)=>request(`/jobs/${id}/${action}`,{method:'POST'}).then(load).catch(error=>setError(error.message));return <main><button className="back" onClick={back}>Dashboard</button><header><div><p className="eyebrow">QUEUE</p><h1>Jobs & logs</h1></div><button className="secondary" onClick={load}>Refresh</button></header>{error&&<p className="error">{error}</p>}<div className="table-wrap"><table><thead><tr><th>Type</th><th>Status</th><th>Attempts</th><th>Error</th><th>Action</th></tr></thead><tbody>{jobs.map(job=><tr key={job.id}><td>{job.kind}</td><td><Badge status={job.status}/></td><td>{job.attempts}/{job.max_attempts}</td><td className="error">{job.error}</td><td>{job.status==='queued'&&<button className="secondary" onClick={()=>control(job.id,'pause')}>Pause</button>}{job.status==='paused'&&<button onClick={()=>control(job.id,'resume')}>Resume</button>}{job.status==='failed'&&<button onClick={()=>control(job.id,'retry')}>Retry</button>}</td></tr>)}</tbody></table></div><section className="settings"><h2>Recent logs</h2>{logs.map(log=><p key={log.id}><small>{new Date(log.created_at).toLocaleString()} · {log.level}</small><br/>{log.message}</p>)}</section></main>; }
function App(){const [chosen,setChosen]=useState<Channel|null>(null);const [showJobs,setShowJobs]=useState(false);if(showJobs)return <JobsPage back={()=>setShowJobs(false)}/>;return <><button className="secondary jobs-button" onClick={()=>setShowJobs(true)}>Jobs & logs</button>{chosen?<ChannelPage channel={chosen} back={()=>setChosen(null)}/>:<Dashboard select={setChosen}/>}</>;}
createRoot(document.getElementById('root')!).render(<App/>);
